<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/private_storage.php';
$logical = $_GET['f'] ?? '';
if (!is_string($logical)) throw new SecurityFault('FILE_PATH_INVALID', 'Invalid file path.', 400);
validate_private_logical_path($logical);
$pdo = get_db();
if (!can_read_private_file($pdo, $logical, (int)$_SESSION['user_id'])) throw new SecurityFault('PERMISSION_DENIED', 'Permission denied.', 403);
$stmt = $pdo->prepare('SELECT * FROM private_files WHERE logical_path = ?');
$stmt->execute([$logical]);
$file = $stmt->fetch();
$root = private_storage_root();
$physical = realpath($root . DIRECTORY_SEPARATOR . substr($logical, 8));
if (!$file || $physical === false || !path_within($physical, $root) || !is_file($physical)) throw new SecurityFault('FILE_NOT_FOUND', 'File not found.', 404);
if (!hash_equals($file['sha256'], (string)hash_file('sha256', $physical))) throw new SecurityFault('FILE_INTEGRITY_INVALID', 'File integrity check failed.', 503);
security_audit($pdo, 'file_downloaded', 'private_file', (int)$file['id']);
while (ob_get_level()) ob_end_clean();
$name = rawurlencode(basename($logical));
$image = str_starts_with($file['mime_type'], 'image/');
header('Content-Type: ' . $file['mime_type']);
header('Content-Length: ' . $file['byte_size']);
header('Content-Disposition: ' . ($image ? 'inline' : 'attachment') . '; filename="' . $name . '"');
header('Content-Security-Policy: sandbox; default-src \'none\'');
header('Cache-Control: private, no-store');
header('X-Content-Type-Options: nosniff');
readfile($physical);
